//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseEntry.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemRight
    {
        public int RightID { get; set; }
        public bool Enabled { get; set; }
    
        public virtual SecurityRole SecurityRole { get; set; }
        public virtual SystemMenu SystemMenu { get; set; }
    }
}
