//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FunctionResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FunctionResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.FunctionResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Complete Entries 的本地化字符串。
        /// </summary>
        internal static string EntryControllerBatchCompleteEntry {
            get {
                return ResourceManager.GetString("EntryControllerBatchCompleteEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import Entries 的本地化字符串。
        /// </summary>
        internal static string EntryControllerBatchCreateEntry {
            get {
                return ResourceManager.GetString("EntryControllerBatchCreateEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Entries 的本地化字符串。
        /// </summary>
        internal static string EntryControllerBatchEditEntry {
            get {
                return ResourceManager.GetString("EntryControllerBatchEditEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Complete Entry 的本地化字符串。
        /// </summary>
        internal static string EntryControllerCompleteEntry {
            get {
                return ResourceManager.GetString("EntryControllerCompleteEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Entry 的本地化字符串。
        /// </summary>
        internal static string EntryControllerCreateEntry {
            get {
                return ResourceManager.GetString("EntryControllerCreateEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Entry 的本地化字符串。
        /// </summary>
        internal static string EntryControllerEditEntry {
            get {
                return ResourceManager.GetString("EntryControllerEditEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Entry Management 的本地化字符串。
        /// </summary>
        internal static string EntryControllerEntryIndex {
            get {
                return ResourceManager.GetString("EntryControllerEntryIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        internal static string HomeIndex {
            get {
                return ResourceManager.GetString("HomeIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product Report 的本地化字符串。
        /// </summary>
        internal static string ReportControllerProductReport {
            get {
                return ResourceManager.GetString("ReportControllerProductReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Weight Report 的本地化字符串。
        /// </summary>
        internal static string ReportControllerWeightReport {
            get {
                return ResourceManager.GetString("ReportControllerWeightReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change Password 的本地化字符串。
        /// </summary>
        internal static string UserControllerChangePassword {
            get {
                return ResourceManager.GetString("UserControllerChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Role 的本地化字符串。
        /// </summary>
        internal static string UserControllerCreateRole {
            get {
                return ResourceManager.GetString("UserControllerCreateRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create User 的本地化字符串。
        /// </summary>
        internal static string UserControllerCreateUser {
            get {
                return ResourceManager.GetString("UserControllerCreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Role 的本地化字符串。
        /// </summary>
        internal static string UserControllerDeleteRole {
            get {
                return ResourceManager.GetString("UserControllerDeleteRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable/Disable Right 的本地化字符串。
        /// </summary>
        internal static string UserControllerEnableRight {
            get {
                return ResourceManager.GetString("UserControllerEnableRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable/Disable User 的本地化字符串。
        /// </summary>
        internal static string UserControllerEnableUser {
            get {
                return ResourceManager.GetString("UserControllerEnableUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right Management 的本地化字符串。
        /// </summary>
        internal static string UserControllerRightIndex {
            get {
                return ResourceManager.GetString("UserControllerRightIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Management 的本地化字符串。
        /// </summary>
        internal static string UserControllerUserIndex {
            get {
                return ResourceManager.GetString("UserControllerUserIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Entry Manager 的本地化字符串。
        /// </summary>
        internal static string VirtualEntry {
            get {
                return ResourceManager.GetString("VirtualEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Report 的本地化字符串。
        /// </summary>
        internal static string VirtualReport {
            get {
                return ResourceManager.GetString("VirtualReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User And Right 的本地化字符串。
        /// </summary>
        internal static string VirtualUserAndRight {
            get {
                return ResourceManager.GetString("VirtualUserAndRight", resourceCulture);
            }
        }
    }
}
