//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SiteCommonResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SiteCommonResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SiteCommonResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Action 的本地化字符串。
        /// </summary>
        internal static string ActionColumnTitle {
            get {
                return ResourceManager.GetString("ActionColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New! 的本地化字符串。
        /// </summary>
        internal static string ActionCreateToolTip {
            get {
                return ResourceManager.GetString("ActionCreateToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete! 的本地化字符串。
        /// </summary>
        internal static string ActionDeleteToolTip {
            get {
                return ResourceManager.GetString("ActionDeleteToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password is not same between twice. 的本地化字符串。
        /// </summary>
        internal static string AlertErrorPasswordNotConfirm {
            get {
                return ResourceManager.GetString("AlertErrorPasswordNotConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attention! 的本地化字符串。
        /// </summary>
        internal static string AlertInfoTitle {
            get {
                return ResourceManager.GetString("AlertInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The admin account will disabled when a valid account created or enabled. 的本地化字符串。
        /// </summary>
        internal static string AlertWarningHasUser {
            get {
                return ResourceManager.GetString("AlertWarningHasUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use admin account to sign in and create or enable a valid account. 的本地化字符串。
        /// </summary>
        internal static string AlertWarningNoUser {
            get {
                return ResourceManager.GetString("AlertWarningNoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning! 的本地化字符串。
        /// </summary>
        internal static string AlertWarningTitle {
            get {
                return ResourceManager.GetString("AlertWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please sign in. 的本地化字符串。
        /// </summary>
        internal static string AlertWarningUnSignIn {
            get {
                return ResourceManager.GetString("AlertWarningUnSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change password successfully. 的本地化字符串。
        /// </summary>
        internal static string MessageChangePasswordSuccessfully {
            get {
                return ResourceManager.GetString("MessageChangePasswordSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create role sucessfully. 的本地化字符串。
        /// </summary>
        internal static string MessageCreateRoleSuccessfully {
            get {
                return ResourceManager.GetString("MessageCreateRoleSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create user sucessfully. 的本地化字符串。
        /// </summary>
        internal static string MessageCreateUserSuccessfully {
            get {
                return ResourceManager.GetString("MessageCreateUserSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The default password of user is : 123456 的本地化字符串。
        /// </summary>
        internal static string MessageDefaultPassword {
            get {
                return ResourceManager.GetString("MessageDefaultPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete role sucessfully. 的本地化字符串。
        /// </summary>
        internal static string MessageDeleteRoleSuccessfully {
            get {
                return ResourceManager.GetString("MessageDeleteRoleSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable role sucessfully. 的本地化字符串。
        /// </summary>
        internal static string MessageDisableRoleSuccessfully {
            get {
                return ResourceManager.GetString("MessageDisableRoleSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable user sucessfully. 的本地化字符串。
        /// </summary>
        internal static string MessageDisableUserSuccessfully {
            get {
                return ResourceManager.GetString("MessageDisableUserSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable role sucessfully. 的本地化字符串。
        /// </summary>
        internal static string MessageEnableRoleSuccessfully {
            get {
                return ResourceManager.GetString("MessageEnableRoleSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable user sucessfully. 的本地化字符串。
        /// </summary>
        internal static string MessageEnableUserSuccessfully {
            get {
                return ResourceManager.GetString("MessageEnableUserSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login sucessfully. 的本地化字符串。
        /// </summary>
        internal static string MessageLoginSucessfully {
            get {
                return ResourceManager.GetString("MessageLoginSucessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operate successfully. 的本地化字符串。
        /// </summary>
        internal static string MessageOperateSuccessfully {
            get {
                return ResourceManager.GetString("MessageOperateSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Role has been deleted. 的本地化字符串。
        /// </summary>
        internal static string MessageRoleDeleted {
            get {
                return ResourceManager.GetString("MessageRoleDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save right sucessfully. 的本地化字符串。
        /// </summary>
        internal static string MessageSaveRightSuccessfully {
            get {
                return ResourceManager.GetString("MessageSaveRightSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aggregate :  的本地化字符串。
        /// </summary>
        internal static string TextAggregate {
            get {
                return ResourceManager.GetString("TextAggregate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All 的本地化字符串。
        /// </summary>
        internal static string TextAll {
            get {
                return ResourceManager.GetString("TextAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change 的本地化字符串。
        /// </summary>
        internal static string TextChange {
            get {
                return ResourceManager.GetString("TextChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Complete 的本地化字符串。
        /// </summary>
        internal static string TextComplete {
            get {
                return ResourceManager.GetString("TextComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Completed 的本地化字符串。
        /// </summary>
        internal static string TextCompleted {
            get {
                return ResourceManager.GetString("TextCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Completed Only 的本地化字符串。
        /// </summary>
        internal static string TextCompletedOnly {
            get {
                return ResourceManager.GetString("TextCompletedOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copyright © 2015-2016 CNPC BAOJI OILFIELD MACHINERY CO.,LTD All rights reserved. 的本地化字符串。
        /// </summary>
        internal static string TextCopyright {
            get {
                return ResourceManager.GetString("TextCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create 的本地化字符串。
        /// </summary>
        internal static string TextCreate {
            get {
                return ResourceManager.GetString("TextCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End Date 的本地化字符串。
        /// </summary>
        internal static string TextEndDate {
            get {
                return ResourceManager.GetString("TextEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome {0} ({1})! 的本地化字符串。
        /// </summary>
        internal static string TextFormatUserInfo {
            get {
                return ResourceManager.GetString("TextFormatUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My Ready Task 的本地化字符串。
        /// </summary>
        internal static string TextMyReadyTask {
            get {
                return ResourceManager.GetString("TextMyReadyTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next Month 的本地化字符串。
        /// </summary>
        internal static string TextNextMonth {
            get {
                return ResourceManager.GetString("TextNextMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Access! 的本地化字符串。
        /// </summary>
        internal static string TextNoAccess {
            get {
                return ResourceManager.GetString("TextNoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password Confirm 的本地化字符串。
        /// </summary>
        internal static string TextPasswordConfirm {
            get {
                return ResourceManager.GetString("TextPasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Previous Month 的本地化字符串。
        /// </summary>
        internal static string TextPreviousMonth {
            get {
                return ResourceManager.GetString("TextPreviousMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reject 的本地化字符串。
        /// </summary>
        internal static string TextReject {
            get {
                return ResourceManager.GetString("TextReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Role List 的本地化字符串。
        /// </summary>
        internal static string TextRoleList {
            get {
                return ResourceManager.GetString("TextRoleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        internal static string TextSave {
            get {
                return ResourceManager.GetString("TextSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        internal static string TextSearch {
            get {
                return ResourceManager.GetString("TextSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sign In 的本地化字符串。
        /// </summary>
        internal static string TextSignIn {
            get {
                return ResourceManager.GetString("TextSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sign Out 的本地化字符串。
        /// </summary>
        internal static string TextSignOut {
            get {
                return ResourceManager.GetString("TextSignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Date 的本地化字符串。
        /// </summary>
        internal static string TextStartDate {
            get {
                return ResourceManager.GetString("TextStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System Main Office 的本地化字符串。
        /// </summary>
        internal static string TextSystemMainOffice {
            get {
                return ResourceManager.GetString("TextSystemMainOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uncompleted 的本地化字符串。
        /// </summary>
        internal static string TextUncompleted {
            get {
                return ResourceManager.GetString("TextUncompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update 的本地化字符串。
        /// </summary>
        internal static string TextUpdate {
            get {
                return ResourceManager.GetString("TextUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click here to import records of entry. 的本地化字符串。
        /// </summary>
        internal static string ToolTipBatchCreateEntry {
            get {
                return ResourceManager.GetString("ToolTipBatchCreateEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click here to create a new record of entry. 的本地化字符串。
        /// </summary>
        internal static string ToolTipCreateEntry {
            get {
                return ResourceManager.GetString("ToolTipCreateEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Batch Complete Entry Records 的本地化字符串。
        /// </summary>
        internal static string ViewTitleEntryControllerBatchCompleteEntry {
            get {
                return ResourceManager.GetString("ViewTitleEntryControllerBatchCompleteEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Batch Create Entry Records 的本地化字符串。
        /// </summary>
        internal static string ViewTitleEntryControllerBatchCreateEntry {
            get {
                return ResourceManager.GetString("ViewTitleEntryControllerBatchCreateEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Batch Edit Entry Records 的本地化字符串。
        /// </summary>
        internal static string ViewTitleEntryControllerBatchEditEntry {
            get {
                return ResourceManager.GetString("ViewTitleEntryControllerBatchEditEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Complete Entry Record 的本地化字符串。
        /// </summary>
        internal static string ViewTitleEntryControllerCompleteEntry {
            get {
                return ResourceManager.GetString("ViewTitleEntryControllerCompleteEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Entry Record 的本地化字符串。
        /// </summary>
        internal static string ViewTitleEntryControllerCreateEntry {
            get {
                return ResourceManager.GetString("ViewTitleEntryControllerCreateEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Entry Record 的本地化字符串。
        /// </summary>
        internal static string ViewTitleEntryControllerEditEntry {
            get {
                return ResourceManager.GetString("ViewTitleEntryControllerEditEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome -- Home 的本地化字符串。
        /// </summary>
        internal static string ViewTitleHomeControllerIndex {
            get {
                return ResourceManager.GetString("ViewTitleHomeControllerIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        internal static string ViewTitleHomeControllerNoAccess {
            get {
                return ResourceManager.GetString("ViewTitleHomeControllerNoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Entry Product Report 的本地化字符串。
        /// </summary>
        internal static string ViewTitleReportControllerProductReport {
            get {
                return ResourceManager.GetString("ViewTitleReportControllerProductReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Entry Weight Report 的本地化字符串。
        /// </summary>
        internal static string ViewTitleReportControllerWeightReport {
            get {
                return ResourceManager.GetString("ViewTitleReportControllerWeightReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change Password 的本地化字符串。
        /// </summary>
        internal static string ViewTitleUserControllerChangePassword {
            get {
                return ResourceManager.GetString("ViewTitleUserControllerChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right Manage 的本地化字符串。
        /// </summary>
        internal static string ViewTitleUserControllerRightIndex {
            get {
                return ResourceManager.GetString("ViewTitleUserControllerRightIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sign In 的本地化字符串。
        /// </summary>
        internal static string ViewTitleUserControllerSignIn {
            get {
                return ResourceManager.GetString("ViewTitleUserControllerSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Manage 的本地化字符串。
        /// </summary>
        internal static string ViewTitleUserControllerUserIndex {
            get {
                return ResourceManager.GetString("ViewTitleUserControllerUserIndex", resourceCulture);
            }
        }
    }
}
