//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseEntry.Business.Languages {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EntryModelResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EntryModelResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WarehouseEntry.Business.Languages.EntryModelResource", typeof(EntryModelResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Assemblage Date 的本地化字符串。
        /// </summary>
        public static string AssemblageDate {
            get {
                return ResourceManager.GetString("AssemblageDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assemblage date is required, please enter a valid date. 的本地化字符串。
        /// </summary>
        public static string AssemblageDateRequired {
            get {
                return ResourceManager.GetString("AssemblageDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Completion Date 的本地化字符串。
        /// </summary>
        public static string CompletionDate {
            get {
                return ResourceManager.GetString("CompletionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Completion date is required, please enter a valid date. 的本地化字符串。
        /// </summary>
        public static string CompletionDateRequired {
            get {
                return ResourceManager.GetString("CompletionDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Correction Date 的本地化字符串。
        /// </summary>
        public static string CorrectionDate {
            get {
                return ResourceManager.GetString("CorrectionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Correction date is required, please enter a valid date. 的本地化字符串。
        /// </summary>
        public static string CorrectionDateRequired {
            get {
                return ResourceManager.GetString("CorrectionDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Despatch Date 的本地化字符串。
        /// </summary>
        public static string DespatchDate {
            get {
                return ResourceManager.GetString("DespatchDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Despatch date is required, please enter a valid date. 的本地化字符串。
        /// </summary>
        public static string DespatchDateRequired {
            get {
                return ResourceManager.GetString("DespatchDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Height 的本地化字符串。
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Height is required, please enter a valid decimal. 的本地化字符串。
        /// </summary>
        public static string HeightRequired {
            get {
                return ResourceManager.GetString("HeightRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image No. 的本地化字符串。
        /// </summary>
        public static string ImgNum {
            get {
                return ResourceManager.GetString("ImgNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image number is required, please enter a valid serial number. 的本地化字符串。
        /// </summary>
        public static string ImgNumRequired {
            get {
                return ResourceManager.GetString("ImgNumRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image number is too long, max length is {1}, please try again. 的本地化字符串。
        /// </summary>
        public static string ImgNumStringLength {
            get {
                return ResourceManager.GetString("ImgNumStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inspection Date 的本地化字符串。
        /// </summary>
        public static string InspectionDate {
            get {
                return ResourceManager.GetString("InspectionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inspection date is required, please enter a valid date. 的本地化字符串。
        /// </summary>
        public static string InspectionDateRequired {
            get {
                return ResourceManager.GetString("InspectionDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Length 的本地化字符串。
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Length is required, please enter a valid decimal. 的本地化字符串。
        /// </summary>
        public static string LengthRequired {
            get {
                return ResourceManager.GetString("LengthRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ID 的本地化字符串。
        /// </summary>
        public static string ModelId {
            get {
                return ResourceManager.GetString("ModelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Id is required. 的本地化字符串。
        /// </summary>
        public static string ModelIdRequired {
            get {
                return ResourceManager.GetString("ModelIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Piece Count 的本地化字符串。
        /// </summary>
        public static string PieceCount {
            get {
                return ResourceManager.GetString("PieceCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Piece count is required, please enter a valid decimal. 的本地化字符串。
        /// </summary>
        public static string PieceCountRequired {
            get {
                return ResourceManager.GetString("PieceCountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product Image No. 的本地化字符串。
        /// </summary>
        public static string ProductImgNum {
            get {
                return ResourceManager.GetString("ProductImgNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product image number is required, please enter a valid serial number. 的本地化字符串。
        /// </summary>
        public static string ProductImgNumRequired {
            get {
                return ResourceManager.GetString("ProductImgNumRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product image number is too long, max length is {1}, please try again. 的本地化字符串。
        /// </summary>
        public static string ProductImgNumStringLength {
            get {
                return ResourceManager.GetString("ProductImgNumStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product Name 的本地化字符串。
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product name is required, please enter a valid name. 的本地化字符串。
        /// </summary>
        public static string ProductNameRequired {
            get {
                return ResourceManager.GetString("ProductNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product name is too long, max length is {1}, please try again. 的本地化字符串。
        /// </summary>
        public static string ProductNameStringLength {
            get {
                return ResourceManager.GetString("ProductNameStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project Name 的本地化字符串。
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project name is required, please enter a valid name. 的本地化字符串。
        /// </summary>
        public static string ProjectNameRequired {
            get {
                return ResourceManager.GetString("ProjectNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project name is too long, max length is {1}, please try again. 的本地化字符串。
        /// </summary>
        public static string ProjectNameStringLength {
            get {
                return ResourceManager.GetString("ProjectNameStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project No. 的本地化字符串。
        /// </summary>
        public static string ProjectNum {
            get {
                return ResourceManager.GetString("ProjectNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project number is required, please enter a valid serial number. 的本地化字符串。
        /// </summary>
        public static string ProjectNumRequired {
            get {
                return ResourceManager.GetString("ProjectNumRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project number is too long, max length is {1}, please try again. 的本地化字符串。
        /// </summary>
        public static string ProjectNumStringLength {
            get {
                return ResourceManager.GetString("ProjectNumStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sequence 的本地化字符串。
        /// </summary>
        public static string Sequence {
            get {
                return ResourceManager.GetString("Sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sequence is required, please enter a valid sequence. 的本地化字符串。
        /// </summary>
        public static string SequenceRequired {
            get {
                return ResourceManager.GetString("SequenceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sequence is too long, max length is {1}, please try again. 的本地化字符串。
        /// </summary>
        public static string SequenceStringLength {
            get {
                return ResourceManager.GetString("SequenceStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Soldering Date 的本地化字符串。
        /// </summary>
        public static string SolderingDate {
            get {
                return ResourceManager.GetString("SolderingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Soldering date is required, please enter a valid date. 的本地化字符串。
        /// </summary>
        public static string SolderingDateRequired {
            get {
                return ResourceManager.GetString("SolderingDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stomach Weight 的本地化字符串。
        /// </summary>
        public static string StomachWeight {
            get {
                return ResourceManager.GetString("StomachWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stomach weight is required, please enter a valid decimal. 的本地化字符串。
        /// </summary>
        public static string StomachWeightRequired {
            get {
                return ResourceManager.GetString("StomachWeightRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Suite Count 的本地化字符串。
        /// </summary>
        public static string SuiteCount {
            get {
                return ResourceManager.GetString("SuiteCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Suite count is required, please enter a valid integer. 的本地化字符串。
        /// </summary>
        public static string SuiteCountRequired {
            get {
                return ResourceManager.GetString("SuiteCountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Weight 的本地化字符串。
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Weight is required, please enter a valid decimal. 的本地化字符串。
        /// </summary>
        public static string WeightRequired {
            get {
                return ResourceManager.GetString("WeightRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Width 的本地化字符串。
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Width is required, please enter a valid decimal. 的本地化字符串。
        /// </summary>
        public static string WidthRequired {
            get {
                return ResourceManager.GetString("WidthRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wing Weight 的本地化字符串。
        /// </summary>
        public static string WingWeight {
            get {
                return ResourceManager.GetString("WingWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wing weight is required, please enter a valid decimal. 的本地化字符串。
        /// </summary>
        public static string WingWeightRequired {
            get {
                return ResourceManager.GetString("WingWeightRequired", resourceCulture);
            }
        }
    }
}
